// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsCrm "github.com/acme-kuetix/acme-crm/modules/crm/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["crm"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"crm"+"/"+"crm", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "crm", Impl: transitionsCrm.NewCrmTransitions() }})
	}
}
